131 fix mutations proportion filter on grid view
GenSpectrum/dashboards pull request #134
Opened 2024-04-10 10:23 UTC by JonasKellerer

resolves #131

### Summary

Fixes that the grid view only showed proportions which where in the proportion interval and not the whole row
and also:
  - moves the data calculation out of the MutationsGrid component
  - removes the workaround for gridJs (hidden columns to store data)

### Screenshot

![Bildschirmfoto vom 2024-04-10 12-14-48](https://github.com/GenSpectrum/dashboards/assets/122305307/37496fa5-0c3f-4c03-9876-92fd8afc78f4)

### PR Checklist

- [x] The implemented feature is covered by an appropriate test.

2024-04-10 14:22 UTC, fengelniederhammer requested changes
Looks good, apart from the `objectsEqualWithTolerance` :)

2024-04-11 07:17 UTC, fengelniederhammer approved these changes

2024-04-11 07:17 UTC, fengelniederhammer commented on components/src/preact/mutations/getMutationsGridData.spec.ts
> +    const isApproximatelyEqualRow = (a: MutationsGridDataRow, b: MutationsGridDataRow) => {
I'd prefer to have an `expect` in the function names :)

2024-04-11 07:17 UTC, fengelniederhammer commented on components/src/preact/mutations/getMutationsGridData.spec.ts
> +    const isApproximatelyEqualRow = (a: MutationsGridDataRow, b: MutationsGridDataRow) => {
Maybe add `expect(Object.keys(basesA).length).toBe(Object.keys(basesB).length);`?

2024-04-11 12:58 UTC, JonasKellerer commented on components/src/utils/test-utils.ts
> +            if (Math.abs(obj1[key] - obj2[key]) > tolerance) return false;
This part of the code was removed, since the general typing of `objectsEqualWithTolerance` was too complex for the simple comparison of the output with js floating point inaccuracy. It was turned into a targeted compare in `expectRowsAreApproximatelyEqual`.

2024-04-11 13:49 UTC, merged