feat(components): provide reference genome to all components
GenSpectrum/dashboards pull request #137
Opened 2024-04-11 12:48 UTC by JonasKellerer

resolves #92

### Summary

Provides the reference genome to all `gs-app` components through a context provider.
A general mock is introduced in `preview.ts`, since the reference genome is needed by all components which use `gs-app`. Specific values of the reference genome can be overwritten by targeted mocks in each story. 

### Screenshot

### PR Checklist

- [ ] The implemented feature is covered by an appropriate test.

2024-04-11 14:03 UTC, fengelniederhammer requested changes
Looks good :+1: 

I think we should handle the case better when LAPIS fails (or is extremely slow) to deliver the reference genomes.

2024-04-11 14:03 UTC, fengelniederhammer commented on components/src/preact/mutations/mutations.tsx
> +    const referenceGenome = useContext(ReferenceGenomeContext);
How about moving this one layer down into `MutationsTabs`?
We could also take it a step further and wrap it in a `useSegments(sequenceType: SequenceType)`. 

Or we could also take it another step further (because that's how we currently exclusively use the segments):
```typescript
function useDisplayedSegments(sequenceType: SequenceType) {
    const referenceGenome = useContext(ReferenceGenomeContext);

    const displayedSegments = getSegmentNames(referenceGenome, sequenceType).map((segment) => ({
        segment,
        label: segment,
        checked: true,
    }));

    return useState<DisplayedSegment[]>(displayedSegments);
}
```

2024-04-11 14:03 UTC, fengelniederhammer commented on components/src/preact/mutations/mutations.tsx
> +    const referenceGenome = useContext(ReferenceGenomeContext);
(Same for mutation comparison)

2024-04-15 10:02 UTC, fengelniederhammer reviewed
The slot thingy seems to work. So let's try it like that.

2024-04-15 10:02 UTC, fengelniederhammer commented on examples/React/src/App.tsx
Looks like this has been formatted either with the wrong prettier settings or with IDE defaults. (Prettier is not installed in this example I think)

2024-04-15 11:27 UTC, JonasKellerer commented on examples/React/src/App.tsx
IntelliJ used its default settings. I found out, that it searches for the prettierrc in the current folder and all its parents. But you can not set it by hand...

2024-04-16 12:28 UTC, fengelniederhammer approved these changes

2024-04-16 12:28 UTC, fengelniederhammer commented on components/src/web-components/app.ts
> +            error: () => html`<p>Error</p>`,
As discussed, let's add a TODO

2024-04-16 13:56 UTC, JonasKellerer commented on components/src/web-components/app.ts
> +            error: () => html`<p>Error</p>`,
There is now this ticket https://github.com/GenSpectrum/dashboards/issues/143, and I added the TODO

2024-04-16 14:01 UTC, merged