160 make location fields configurable
GenSpectrum/dashboards pull request #177
Opened 2024-10-02 12:16 UTC by JonasKellerer

resolves #160

### Summary

This PR makes the location-, lineage-, host-, authors-, authorAffiliations-, submittingLab-, and originatingLab-Field configurable. This required some rework of the views, so get rid of the hard coded keys. 

Most things that changed can be found in `helpers.ts` and the views in `/routes`.

Now each organism has the concept of lineage and clade. 

In the future it might be good to configure each page from a common config. This way there is less duplication. A start can already be found in `components/rsv`.
It would also be nice to use the react components of the dashboard-components. This would make it easier to use them.

### Screenshot

2024-10-02 13:19 UTC, fengelniederhammer requested changes
`http://localhost:4321/covid` shows 

![image](https://github.com/user-attachments/assets/dda905e4-a3cd-4ecb-be72-3ef6c735041d)

2024-10-02 13:30 UTC, JonasKellerer commented
Hm... `http://localhost:4321/covid` seems not to work on main either.

2024-10-02 13:32 UTC, fengelniederhammer commented
> Hm... `http://localhost:4321/covid` seems not to work on main either.

Unfortunate. Then let's make it a separate issue.

2024-10-02 15:17 UTC, fengelniederhammer approved these changes
LGTM :+1:

2024-10-02 15:17 UTC, fengelniederhammer commented on website/src/pages/west-nile/single-variant.astro
> +    getTodayString,
```suggestion
```
seems unused

2024-10-02 15:17 UTC, fengelniederhammer commented on website/src/pages/mpox/single-variant.astro
> +                            },
`clade` and `lineage` are here, because they have to match the keys used in `getLapisVariantQuery`? Let's connect them via common constants?

2024-10-02 15:17 UTC, fengelniederhammer commented on website/src/pages/covid/single-variant.astro
> +console.log('routeData.variantFilter', routeData.variantFilter);
Looks like a leftover :)

2024-10-02 15:17 UTC, fengelniederhammer commented on website/src/pages/covid/single-variant.astro
> +                                    'lineage' in routeData.variantFilter ? routeData.variantFilter.lineage : undefined,
```suggestion
                                routeData.variantFilter.lineage ?? undefined,
```
Doesn't that do the same?

2024-10-02 15:30 UTC, JonasKellerer commented
> > Hm... `http://localhost:4321/covid` seems not to work on main either.
> 
> Unfortunate. Then let's make it a separate issue.
Ther is now #186

2024-10-04 08:13 UTC, JonasKellerer commented on website/src/routes/rsvB.ts
Ah, I missed that. Good catch.

2024-10-04 08:34 UTC, merged