feat!(components): all input components should have a `initialValue` attribute
GenSpectrum/dashboards pull request #203
Opened 2024-05-02 13:27 UTC by fengelniederhammer

resolves #190

### Summary

BREAKING CHANGE: rename `value` to `initialValue` in `gs-location-filter`

### Screenshot

### PR Checklist

- [x] All necessary documentation has been adapted.
- [x] The implemented feature is covered by an appropriate test.

2024-05-07 09:18 UTC, JonasKellerer requested changes
Nice changes. In the web components stories, some things are not working.

2024-05-07 09:18 UTC, JonasKellerer commented on components/src/web-components/input/date-range-selector-component.tsx
> +    customSelectOptions: CustomSelectOption<CustomLabel>[] = [];
We might want to document somehow, that the template type of this component must match the provided labels of the "customSelectOptions".

2024-05-07 09:18 UTC, JonasKellerer commented on components/src/web-components/input/date-range-selector-component.stories.ts
In storybook there is no handle to set the initial value.

2024-05-07 09:18 UTC, JonasKellerer commented on components/src/web-components/input/location-filter-component.stories.ts
> +        initialValue: '',
When I set the initialValue in the story the component does not show the initial value.

2024-05-07 09:18 UTC, JonasKellerer commented on components/src/web-components/input/text-input-component.tsx
In storybook there is no handle to set the initial value.

2024-05-07 09:18 UTC, JonasKellerer commented on components/src/web-components/input/mutation-filter-component.stories.ts
> +        initialValue: ['A123T'],
Same as for the location filter component. Changing this property does not change the showed component.

2024-05-07 11:48 UTC, fengelniederhammer commented on components/src/web-components/input/date-range-selector-component.tsx
> +    customSelectOptions: CustomSelectOption<CustomLabel>[] = [];
Certainly, but I would leave that to #199

2024-05-07 12:25 UTC, fengelniederhammer commented on components/src/web-components/input/location-filter-component.stories.ts
> +        initialValue: '',
The reason is the `useState` in the Preact component. It doesn't create a new component, but it leave the old one intact, which already has the state set. So the `initialValue` doesn't do anything if you change it on an already mounted component.

2024-05-07 12:33 UTC, JonasKellerer commented on components/src/web-components/input/location-filter-component.stories.ts
> +        initialValue: '',
True. We might need to add this to the docu, so the user has to refresh the storybook to see the change. Otherwise one could think this is a bug.

2024-05-07 12:39 UTC, fengelniederhammer commented on components/src/web-components/input/location-filter-component.stories.ts
> +        initialValue: '',
Is it enough to add this to the component docs?

2024-05-08 07:14 UTC, JonasKellerer approved these changes
LGTM

2024-05-08 07:31 UTC, merged