235 make info button mobile friendly
GenSpectrum/dashboards pull request #246
Opened 2024-05-20 11:53 UTC by JonasKellerer

resolves #235

### Summary

The info component, now resizes to a smaller size, when on a small screen. This way it should not go outside of the screen. It still is next to the info button. (When the maintainer of a website decides to put the info button outside of the viewport also the info text will be displayed outside. This can also be the case for the prevalence over time component on mobile view. This issue will be adressed in #234)
Also the mutation filter component is redisigned, so it works better with the info button and is more similar to loculus input field.

### Screenshot

![Bildschirmfoto 2024-05-20 um 12 26 51](https://github.com/GenSpectrum/dashboards/assets/122305307/2640f68e-5ece-4020-9d9b-8aa469d3c3e0)
![Bildschirmfoto 2024-05-20 um 13 33 03](https://github.com/GenSpectrum/dashboards/assets/122305307/740044bc-e43e-49d3-9805-0e998c5f40b6)

### PR Checklist

- [x] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

2024-05-21 08:15 UTC, fengelniederhammer requested changes

2024-05-21 08:15 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +            <div className='absolute top-1 right-1'>
This places the info button outside of the component (in most cases). That's probably not the desired behavior?

2024-05-21 08:15 UTC, fengelniederhammer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +
```suggestion
```

2024-05-21 08:15 UTC, fengelniederhammer commented on components/src/web-components/input/gs-mutation-filter.tsx
> -    height: string = '6.5rem';
Actually this is breaking. But I think it's ok if we don't label it as breaking as long as we still take this into the 0.3 release.

2024-05-21 08:15 UTC, fengelniederhammer commented on components/src/web-components/input/gs-mutation-filter.stories.ts
> -                    .height=${args.height}
Please also adapt the code example above.

2024-05-21 08:15 UTC, fengelniederhammer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/73ff15c1-8950-444b-8269-10dcd41dba07)

The size of the info box in the top right diagram of the React example is wrong for some reason.

2024-05-27 09:07 UTC, JonasKellerer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +            <div className='absolute top-1 right-1'>
This is not intended. The absolute keyword takes the next fixed parent. This should have been the surrounding div, but was the document. It is changed now.

2024-05-27 09:08 UTC, JonasKellerer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +
No longer in this PR

2024-05-27 09:08 UTC, JonasKellerer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        <form className='w-full  border boder-gray-300 rounded-md' onSubmit={handleSubmit} ref={formRef}>
No longer in this PR

2024-05-27 09:12 UTC, JonasKellerer commented on components/src/web-components/input/gs-mutation-filter.tsx
> -    height: string = '6.5rem';
Marked now as breaking.

2024-05-27 09:14 UTC, JonasKellerer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
Set to a fixed size for now.

2024-05-27 09:36 UTC, JonasKellerer commented
I now changed the PR, so it uses floating-ui to show the tooltip info. This can then be used for other tooltip actions, like mutation filter.

This now opens a band stretching from side to side with the info. 

On desktop:
![grafik](https://github.com/GenSpectrum/dashboards/assets/122305307/24c5aaf4-ebbc-403c-83ec-74e355ce11b7)

On Mobile:
![grafik](https://github.com/GenSpectrum/dashboards/assets/122305307/75be9c90-cb22-448c-8639-becc8fb1ad2d)


I also tried to look for info buttons an my own websearches. I only found this on amazon:
![grafik](https://github.com/GenSpectrum/dashboards/assets/122305307/6fbcceb2-71dc-498a-8c2a-fbf3cac1d56b)
This opens the info in a modal. On mobile the modal comes from the bottom.

2024-05-27 12:34 UTC, fengelniederhammer requested changes
Actually looks good, some minor styling things... :)

2024-05-27 12:34 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +                        className='grow'
```suggestion
                        className='grow input'
```

or something similar, so that the text in the field gets a little marging to the border. (The `+` button needs to be centered then again)

2024-05-27 12:34 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        </form>
My browsers (Chrome and Firefox) highlight the currently focused field.

Before:
![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/56e3def9-aeb9-44a2-bb48-cc0a7efb0f0b)

After:
![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/67ea12e3-a4a8-47b9-a6f7-3e7ad7487e9b)

Should we try to get the "+" button inside the box again, so that browser highlight and our brodered box match?

2024-05-27 12:34 UTC, fengelniederhammer commented on components/src/preact/components/info.tsx
I think a normal close button would still be good (to get some visual feedback that you can close the info box).

2024-05-27 12:34 UTC, fengelniederhammer commented on components/src/preact/components/info.tsx
> +                className='bg-white p-2 border border-gray-100 flex flex-col shadow-lg rounded overflow-y-auto'
```suggestion
                className='bg-white p-2 border border-gray-100 flex flex-col shadow-lg rounded overflow-y-auto opacity-90'
```

2024-05-27 13:15 UTC, JonasKellerer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        </form>
I fixed it, so the focus no longer focuses on the input field, but on the surrounding.

2024-05-27 13:23 UTC, JonasKellerer commented on components/src/preact/components/info.tsx
There is now a button at the bottom. It will turn slightly blue, when hovered.

![grafik](https://github.com/GenSpectrum/dashboards/assets/122305307/dc0494c7-486c-4935-a83a-81de12ccc1b4)

2024-05-28 07:07 UTC, fengelniederhammer approved these changes

2024-05-28 07:07 UTC, fengelniederhammer commented on components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx
If I make the diagram small:
![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/f4b11ad6-4f9b-48f2-9462-ceceef20d035)

It will still show a large info box:
![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/cddbb905-e94b-49d1-a563-b198363d7ae7)

Should we fix this? Or do we leave it for now?

2024-05-28 07:07 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +            </div>
I'm not sure whether it's good to have this button exactly on the corner. But let's see whether it works. We can still change that later.

2024-05-28 07:11 UTC, JonasKellerer commented on components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx
I tried to make the info more like a modal. So it is not dependent on the height of the container. So for me this is a feature not a bug ;)

2024-05-28 07:13 UTC, JonasKellerer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +            </div>
I did not find any better place to put it, without using additional space in the case when no mutation is selected.

2024-05-28 07:45 UTC, merged