feat(website): add view for Swiss wastewater data from WISE
GenSpectrum/dashboards pull request #299
Opened 2024-11-14 16:17 UTC by chaoran-chen

This PR adds RSV and influenza mutation over time plots for Switzerland based on wastewater data from WISE. It depends on https://github.com/GenSpectrum/dashboard-components/pull/504.

Data are fetched from https://wise-loculus.genspectrum.org/.

## Screenshots

<img width="287" alt="image" src="https://github.com/user-attachments/assets/7faac77d-cdab-4915-9028-6c575b92ca2e" />

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/b0086fdf-458f-458c-84bc-200c132863e7" />

2025-01-21 14:16 UTC, JonasKellerer requested changes
Great to see the wastewater data on our page. 
My comments are mostly from the desgin perspective and integration of the new pages in our current setup.

I think the muted color of wastewater is a little bit strong in comparison to the other colors. 
![grafik](https://github.com/user-attachments/assets/ae4ca1fd-473c-4464-841e-8e6e9823d6de)

I think we need to adapt the "Data sources" page, to also cover the wastewater data.

On the "home" page, do we want to add something to "Open Source Tooling". We could mention the wastewater.
@chaoran-chen Do we need to add something to the "How to cite" section?

The data for influneca contains some short code for the locations:
![grafik](https://github.com/user-attachments/assets/1084fc3e-e122-48d9-a47a-59cd7aef0a70)
The data for rsv does not:
![grafik](https://github.com/user-attachments/assets/5b0eab6a-ade4-4071-828d-50dea0f36c7a)

I just saw it now, (but this is maybe a topic for the components), but do we also want the proportion selector on the wastewater-mutations-over-time component?

2025-01-21 14:16 UTC, JonasKellerer commented on website/src/layouts/base/header/getPathogenMegaMenuSections.ts
> +                label: 'Influenza',
I think this is not related to this PR, but for our organsims, we have named one "flu/h5n1" in the url and here we name it "influenca".

2025-01-21 14:16 UTC, JonasKellerer commented on website/src/pages/swiss-wastewater/rsv.astro
> +                        <h2 class='font-bold'>{reference}</h2>
Same as above.

2025-01-21 14:16 UTC, JonasKellerer commented on website/src/pages/swiss-wastewater/rsv.astro
> +    <div class='m-6'>
```suggestion
    <div class='p-2'>
```
The components are very close to the border of the view port. We don't need this on the other pages, since we have our filters there. 
Since, I would remove the headline, we don't need the space above.

2025-01-21 14:25 UTC, fengelniederhammer commented
> The data for influneca contains some short code for the locations:
> ![grafik](https://private-user-images.githubusercontent.com/122305307/405246244-1084fc3e-e122-48d9-a47a-59cd7aef0a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0Njk3NzYsIm5iZiI6MTczNzQ2OTQ3NiwicGF0aCI6Ii8xMjIzMDUzMDcvNDA1MjQ2MjQ0LTEwODRmYzNlLWUxMjItNDhkOS1hNDdhLTU5Y2Q3YWVmMGE3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyMVQxNDI0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGMxYzJhMWM0ZmJjNGQxYjA5Zjk4ODUxZDg3ZDMwZWZkMzBhNGM1ZjhhZTQxZmU2MGQ5NzY3ODc0NmVlZGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OmTp1wG3HfRQMyxVx3MuPu_Kj8VxUD-lcOxhjqpu3vM)
> The data for rsv does not:

We have no influence on that - the location names are taken from the data.

2025-01-21 14:27 UTC, fengelniederhammer commented on website/src/types/dataOrigins.ts
> +    [dataOrigins.wise]: { name: 'WISE', href: 'https://wise.ethz.ch' },
I don't think so. The page doesn't seem to have url based routing.

2025-01-21 14:27 UTC, fengelniederhammer commented on website/src/types/wastewaterConfig.ts
> +    pages: {
Hm. Or `url`s? ;)

2025-01-21 14:32 UTC, fengelniederhammer commented on website/src/pages/swiss-wastewater/influenza.astro
> +            <span class='mr-4 p-2 text-xs'>Data last updated: {lastUpdatedDate ?? 'unknown'}</span>
I simply forgot to delete this...

2025-01-21 15:09 UTC, fengelniederhammer commented on website/src/pages/swiss-wastewater/rsv.astro
> +    <div class='m-6'>
Actually I like the `m-6` more. I changed it to `m-4` because IMO it looks better on mobile with a little less margin.

2025-01-21 15:16 UTC, fengelniederhammer commented on website/src/layouts/base/header/getPathogenMegaMenuSections.ts
> +    sections.push({
As discussed: Let's leave it here for now. We'll discuss it in the next dashboards meeting.

2025-01-21 15:19 UTC, fengelniederhammer commented on website/src/layouts/base/header/getPathogenMegaMenuSections.ts
>  export function getPathogenMegaMenuSections() {
I'm not sure about this one. It's still the "Pathogens" menu entry (although wastewater is no pathogen itself).

2025-01-21 15:23 UTC, fengelniederhammer commented on website/src/types/wastewaterConfig.ts
> +    pages: {
Thinking about it, page is probably good. It's a webpage with a certain url. Maybe it contains a view, but that's something else.

2025-01-21 15:47 UTC, JonasKellerer commented on website/src/types/wastewaterConfig.ts
> +    pages: {
Was no serious comment. But your logic could also apply to the views.

2025-01-22 07:16 UTC, fengelniederhammer commented on website/src/layouts/base/header/getPathogenMegaMenuSections.ts
>  export function getPathogenMegaMenuSections() {
Agreed :+1:

2025-01-22 07:16 UTC, fengelniederhammer commented
> Before we merge this, we need to make shure to have the waste water components in the release of the components.

The correct version (0.13.1) is already on main.

2025-01-22 07:17 UTC, merged

2025-01-22 07:48 UTC, gordonkoehn commented
I'm thrilled to see the integration happen, right here!