refactor: use daisyui for tabs and containers
GenSpectrum/dashboards pull request #46
Opened 2024-03-09 10:02 UTC by JonasKellerer

### Summary
- refactor container components to make them more modular
- more use of daisyui features like tabs and dropdown

### Screenshot
![grafik](https://github.com/GenSpectrum/dashboards/assets/122305307/d045c84c-6c9d-41fe-83fb-905b46bac43c)

### PR Checklist
~~- [ ] The implemented feature is covered by an appropriate test.~~
(There are no tests yet)

2024-03-09 10:05 UTC, JonasKellerer commented on components/src/components/container/component-checkbox-selector.ts
> +                                        @change=${() => {
I'm not sure if this is a nice design. What do you think @fengelniederhammer ?

The idea was, that this element can be initialized through its props, but changes are handled internally and only the change is broadcasted through the Event. 
However, we need to have the same structure of state and setState in the parent component, which uses this component (see `mutations.ts`). So it might be easier to use this component without the internal state.

2024-03-09 12:06 UTC, chaoran-chen commented
Would it be possible to leave the tabs at the bottom while minimize the whitespace

2024-03-09 12:43 UTC, chaoran-chen commented
Sorry for the very brief comment earlier. The tabs look much better than the previous ones!

To explain what I would like to improve, something that I don't like about the CoV-Spectrum plots is that the actual plots are really small: in this example, the plot only covers 36.8% of the area of a component:

![image](https://github.com/GenSpectrum/dashboards/assets/18666552/f55149ec-ccef-4f80-8a12-5d879e7fbddd)

With the new design, I tried to minimize the whitespace. Even with the very large title, the plot covers 71% of the area. Hereby, it was a conscious decision to have the tabs on the same row as the scale options (linear/logarithmic) and the question mark button.

![image](https://github.com/GenSpectrum/dashboards/assets/18666552/a1a75f01-5bf6-4af4-ad86-b151b9cb9cca)

With the design of this PR, there is more whitespace and the plot only covers 57.3% of the area and I would like to increase the number.

![image](https://github.com/GenSpectrum/dashboards/assets/18666552/490ae6c6-2160-43ef-85c5-0046443c6a5c)

2024-03-12 10:40 UTC, fengelniederhammer requested changes
Looks good in general :)

* Do we want to write some basic tests for the helper components?
* How do we handle that issue that subcomponents create their own shadow DOM? In this PR or in a separate issue?

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/container/component-checkbox-selector.ts
> +                <div tabindex="0" role="button" class="btn btn-${this.size}">${this.label}</div>
```suggestion
                <div tabindex="0" role="button" class="btn ${this.size}">${this.label}</div>
```
I quite sure that optimization for only actually used css classes doesn't work, if we use them dynamically. Is the `size` prop actually used currently? We can also remove it for now and check later what customization abilities we need here.

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/container/component-checkbox-selector.stories.ts
Do we want to add a basic test for this component?

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/container/component-container.ts
> +                <p class="text-2xl m-4">${this.heading}</p>
Let's use a `h1` or `h2` tag instead?

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/container/component-container.ts
>  @customElement('gs-component-container')
The name doesn't really fit anymore, but we can also change that later.

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/container/component-info.stories.ts
> +        return html` <gs-component-info content=${content}></gs-component-info> `;
![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/3667c40f-ce62-49b5-9632-29051b6c70a0)

The tooltip isn't visible (at least in my Firefox)

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/container/component-tabs.ts
> +                    ?checked=${index === 0}
What does the `?` do here?

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/container/component-info.ts
> +        return html`<div class="tooltip" data-tip=${this.content}>
I can imagine that a tooltip isn't the right tool to display those info texts. Some are probably larger that a usual tooltip. But let's see when we write actual info texts.

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/mutations.stories.ts
> +            <div class="max-w-screen-sm">
We should probably instead make sure that the tab itself isn't larger than necessary.

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/mutations.ts
> -    `;
At some point, we should bring this back in some form (maybe as a separate component?)

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/query/queryRelativeGrowthAdvantage.ts
> +export type RelativeGrowthAdvantageData = {
We can probably also use this type somewhere in this file? Either `export type RelativeGrowthAdvantageData = ReturnType<typeof queryRelativeGrowthAdvantage>` or declaring the response type explicitly, if TS can't infer the response type properly.

2024-03-12 10:40 UTC, fengelniederhammer commented on components/src/components/relative-growth-advantage.ts
> +                    >`;
```suggestion
                    return html` <gs-component-container heading=${this.heading}>
                        No data available.</gs-component-container
                    >`;
```
And the formatting looks quite broken ;)

2024-03-12 10:54 UTC, JonasKellerer commented on components/src/components/container/component-checkbox-selector.ts
> +                <div tabindex="0" role="button" class="btn btn-${this.size}">${this.label}</div>
It is not used. I added it, because we might want to change the size of the text somehow later on. We have many different sizes right now. I removed it here and we can add it later on.

2024-03-12 10:55 UTC, JonasKellerer commented on components/src/components/container/component-checkbox-selector.stories.ts
We do, but there were no tests available at that time ;) I'll add some.

2024-03-12 10:58 UTC, JonasKellerer commented on components/src/components/container/component-container.ts
> +                <p class="text-2xl m-4">${this.heading}</p>
I changed it to h2. h1 seems to me for the heading of the page. The margin is now also gone. However we might want to add this later on with tailwind/typography https://daisyui.com/docs/layout-and-typography/

2024-03-12 11:00 UTC, chaoran-chen commented on components/src/components/container/component-container.ts
> +                <p class="text-2xl m-4">${this.heading}</p>
Hmm, do you know what is the right way to do this in web components? In a normal document, `h1` should be the main title, but I don't know how things should be for components that could be placed at various places (within a sub-subsection that might have a `h4` header or directly as the only content of a page where a `h1` would make sense).

2024-03-12 11:07 UTC, JonasKellerer commented on components/src/components/container/component-info.stories.ts
> +        return html` <gs-component-info content=${content}></gs-component-info> `;
For me its the same. However, the tooltip should open to the top. Daisyui does not render the tooltip depending on the given space to other directions. That is why it cant be seen in the story. I will change the story, so one can see the content. However, I would argue to leave the component it like it is since you suggested to change the info object later on.

2024-03-12 12:36 UTC, JonasKellerer commented on components/src/components/container/component-info.ts
> +        return html`<div class="tooltip" data-tip=${this.content}>
I also think we will need other components to show this. This can only show text. But maybe we want to render also some components.

2024-03-12 12:39 UTC, JonasKellerer commented on components/src/components/mutations.ts
> -    `;
I think a limiting component would be nice. I added a ticket #55

2024-03-12 13:50 UTC, JonasKellerer commented on components/src/query/queryRelativeGrowthAdvantage.ts
> +export type RelativeGrowthAdvantageData = {
I used the ReturnType. However, I could not use it inside, since the type inside has for estimatedAbsoluteNumbers.t type number[] and not type YearMonthDay. But this problem is deeper inside the code. My personal feeling is, that we could use always the unix time inside the code, and only have the user facing side using the temporal objects. But this would be a larger refactor. 
Additionally, I think we should use zodios for parsing the fetch results. However, this would be its own ticket.

2024-03-12 14:24 UTC, JonasKellerer commented on components/src/components/container/component-container.ts
> +                <p class="text-2xl m-4">${this.heading}</p>
Good question. Currently, I can imagine two scenarios:
1: 
  <ExternalComponent>
    <OurComponent />
    <SecondExternal />
   </ExternalComponent>
 2:
   <ExternalComponent>
    <OurComponent >
      <SecondExternal>
    </OurComponent>
   </ExternalComponent>
   
 In case 1 we can set the shadow root to OurComponent. Then the css we use stays inside. But we could also think about passing css to our component. (Or this is what I've read so far). This way users can style our components as they wish to.
 In case 2 I think we have more of a problem, since the SecondExternal component can have also a `h2` component. We can try to bypass this if we use the slot system. In this case the global css will be used for the SecondExternal component (if I read https://css-tricks.com/styling-a-web-component/ correctly).
 But maybe we want to use both versions.

2024-03-13 10:54 UTC, JonasKellerer commented on components/src/components/container/component-checkbox-selector.ts
> +                                        @change=${() => {
As discussed we pass the set method to the component, so we dont have events bubbling through the tree.

2024-03-13 12:01 UTC, fengelniederhammer approved these changes

2024-03-13 12:03 UTC, merged