feat(components): add gs-date-range-changed event to date range selector
GenSpectrum/dashboards pull request #83
Opened 2024-03-20 17:46 UTC by JonasKellerer

Resolves #81, resolves #80

### Summary

This adds a event and a submit button to the date range selector. The event contains the dateFrom and dateTo of the selector.

### Screenshot

![image](https://github.com/GenSpectrum/dashboards/assets/122305307/d3dbfae0-7b46-476e-bd0a-fa2741d2b5c6)

### PR Checklist

- [x] The implemented feature is covered by an appropriate test.

2024-03-21 09:57 UTC, fengelniederhammer requested changes

2024-03-21 09:57 UTC, fengelniederhammer commented on components/src/components/dateRangeSelector/date-range-selector.ts
> +                bubbles: true,
https://developer.mozilla.org/en-US/docs/Web/API/Event/composed

```suggestion
                bubbles: true,
                composed: true,
```

2024-03-21 09:57 UTC, fengelniederhammer commented on components/src/components/dateRangeSelector/date-range-selector.stories.ts
> +            await expect(listenerMock).toHaveBeenCalled();
I think it would also be good to check that the mock has been called with correct values.

2024-03-21 09:57 UTC, fengelniederhammer commented on components/src/components/dateRangeSelector/date-range-selector.ts
>                  />
Actually it would be nice if pressing enter in this field would also trigger the event.

2024-03-21 09:57 UTC, fengelniederhammer commented on components/src/components/dateRangeSelector/date-range-selector.ts
> +            <form class="join">
As discussed: Either we use the submit of this form or we can revert it to a div.

2024-03-21 09:57 UTC, fengelniederhammer commented on components/src/components/dateRangeSelector/date-range-selector.ts
> +                    @change=${(event: Event) => {
As discussed: Selecting a new value here should also trigger the event.

2024-03-21 11:01 UTC, JonasKellerer commented
As discussed we remove the submit button and submit, when the user
- hits enter
- selects one from the predetermined ranges
- leaves the component

2024-03-21 14:58 UTC, JonasKellerer commented
The component now looks like this without the submit button:
![grafik](https://github.com/GenSpectrum/dashboards/assets/122305307/cac50e74-9ece-4600-af02-7180cc13b9bf)

2024-03-25 09:02 UTC, fengelniederhammer commented on components/src/components/dateRangeSelector/date-range-selector.ts
> +                detail: { dateFrom, dateTo },
Ultimately this goes into LAPIS. So I think the event should contain dates that can be consumed by LAPIS, i.e. a string in the correct format (instead of a `Date` object). What do you think @chaoran-chen?

2024-03-25 12:02 UTC, chaoran-chen commented on components/src/components/dateRangeSelector/date-range-selector.ts
> +                detail: { dateFrom, dateTo },
Yes, the output of the selectors should be a [`LapisFilter`](https://github.com/GenSpectrum/dashboards/blob/main/components/src/types.ts#L1).

2024-03-25 13:00 UTC, fengelniederhammer approved these changes
LGTM

2024-03-25 13:01 UTC, merged