58 allow users to set a min proportion
GenSpectrum/dashboards pull request #96
Opened 2024-04-02 12:55 UTC by JonasKellerer

resolves #58

This is a draft and should show how the component could be used. The corresponding tests are still missing. 

### Summary

Adds a new component, which opens a dropdown. In this dropdown, users can select the min and max proportion.
Currently, this only applies to substitutions and deletions. Insertions stay untouched.

Currently, the tab switches back to the first tab when changing the proportion. This can only be fixed, once we can mark the current selected tab. This is similar to #88.

### Screenshot

![grafik](https://github.com/GenSpectrum/dashboards/assets/122305307/c4ca9316-547f-4685-a453-34f666b0f1a0)

### PR Checklist

- [ ] The implemented feature is covered by an appropriate test.

2024-04-02 13:19 UTC, fengelniederhammer reviewed
Looks good in general :+1:

2024-04-02 13:19 UTC, fengelniederhammer commented on components/src/preact/components/percent-intput.tsx
> +    const [error, setError] = useState(!percentageInRange(percentage));
```suggestion
    const [isError, setIsError] = useState(!percentageInRange(percentage));
```

2024-04-02 13:19 UTC, fengelniederhammer commented on components/src/preact/components/percent-intput.tsx
> +            setError(false);
We also need to check this if `value` changes by changing the value via the slider:

* Input wrong value
* Input box gets read (as expected)
* change the value via the slider
* Input box stays red (should go back to "no error")

2024-04-03 08:37 UTC, chaoran-chen commented
Thanks, @JonasKellerer, it looks beautiful! Is it possible to enter small numbers? I.e., can we, for example, filter for mutations in the range of 0.01%-1%. That would be quite useful.

2024-04-03 12:06 UTC, JonasKellerer commented
Currently the precision is set to 3 digits, so 0.001% is possible. The up down arrows change the percentage by 0.1%. (I thought this is more often the use case). But I can also change this to 3 digits as well.

2024-04-03 14:42 UTC, fengelniederhammer requested changes

2024-04-03 14:42 UTC, fengelniederhammer commented on components/src/preact/components/proportion-selector.tsx
![image](https://github.com/GenSpectrum/dashboards/assets/92720311/cd2bf7cc-1273-43dd-81e0-1bdc6a3d39c3)

By typing values into the inputs, I can generate invalid states. :)

2024-04-03 14:42 UTC, fengelniederhammer commented on components/src/preact/mutations/mutations.tsx
> +    const filterByProportion = (mutationEntry: MutationEntry[]) => {
```suggestion
    const filterByProportion = (mutationEntries: MutationEntry[]) => {
```

2024-04-03 14:42 UTC, fengelniederhammer commented on components/src/preact/mutations/mutations.tsx
[video](https://github.com/GenSpectrum/dashboards/assets/92720311/8f8681e4-40e8-4d55-88bb-c7eb73435e6a)

When dragging one of those sliders, the table gets rerendered on every tick. Maybe we want to avoid that? But I also don't want to block on this.

2024-04-04 15:10 UTC, fengelniederhammer approved these changes

2024-04-04 15:22 UTC, JonasKellerer commented on components/src/preact/components/proportion-selector.tsx
As discussed we postpone this to later in this ticket: #115

2024-04-04 15:23 UTC, JonasKellerer commented on components/src/preact/mutations/mutations.tsx
As discussed, this is intended behavior. Users should be able to see the changes immediately. (Until this takes up to much computing power.)

2024-04-04 15:25 UTC, merged